### ISSUE TITLE
Merge data_readers.clj on the fly

### ISSUE THREAD

**Issue by tonsky** [tonsky/uberdeps#1]

**Comment by thenonameguy** [comment]
It would be nice if merging of arbitrary classpath resources was supported by the lib. The generality could pave the way for supporting Duct-style applications:
https://github.com/duct-framework/duct/issues/92

Essentially the `:uberjar-merge-with` option of leiningen should be extracted:
https://github.com/technomancy/leiningen/blob/87a6af9a12d5c479bfbb51f50b85c3fa4c2650a0/leiningen-core/src/leiningen/core/project.clj#L242

**Comment by tonsky** [comment]
Thanks for the pointer!

**Comment by WhittlesJr** [comment]
I ran into this as well. I need to be able to merge resource files a la `:uberjar-merge-with`.

**Comment by tonsky** [comment]
@WhittlesJr just to be clear: you need to merge data_readers or you need a custom merger?

I plan to fix these in the nearest future

**Comment by WhittlesJr** [comment]
I believe what I need is a custom merger. I'm working with duct just like @thenonameguy, and I need to merge a bunch of .edn files that shows up with the same classpath from multiple projects. Here's the issue as experienced by a boot user: https://github.com/duct-framework/duct/issues/102
