### ISSUE TITLE
Specify Main-class: in META-INF/MAINFEST.MF

### ISSUE THREAD

**Issue by tonsky** [tonsky/uberdeps#13]
Also would be great to have an option to specify Main-class: in META-INF/MAINFEST.MF

_Originally posted by @maxp in https://github.com/tonsky/uberdeps/issues/12#issuecomment-522596398_

**Comment by maxp** [comment]
That feature needed to run "single compiled binary" as `java -jar myapp.jar`.

Some aot also needed before that
`clj -e "(set! *compile-path* \"${CLASSES_TMP}\") (compile '${MAIN_FUNC})"`
