### ISSUE TITLE
Cannot find main class on windows

### ISSUE THREAD

**Issue by mmmdreg** [tonsky/uberdeps#16]
At work we have to use windows, and it seems there is an issue loading the main class in the jar generated by uberdeps. The same code works fine on Linux. 

Setup:
- minimal code with a gen-class that just does a println
- :paths [“src” “classes”]
- first aot with (compile ‘app.core)
- then uberjar
- then try java -cp out.jar clojure.main -m app.core

On windows:
Execution error FileNotFound...
Could not locate app/core__init, app/core.clj...

Unzipping the jar, all these files are there as expected. Furthermore, using the unzipped dir as the class path works as expected. 

Using a reply with org.clojure/java.classpath against the jar, I can list the file names in the jar which also include the class (and source) files as expected. 

Exactly the same code on a Linux box works fine. 

Any ideas on which part of the toolchain is causing these issues? 

For the record, uberjar created with lein work fine, and the contents do not look particularly different. 

More info:
Clojure 1.10.1
OpenJDK 11.0.3

**Comment by mmmdreg** [comment]
Ok so I ran ‘jar tf out.jar | grep app’ against both the Linux and windows generated jars. The Linux one has files like app/core.class, whereas the windows one has app\core.class (note the slash direction). 

As far as I am aware, the path separator for jar files needs to be a forward slash. 

Is it up to uberdeps to convert the windows slashes into the correct separator?

**Comment by mmmdreg** [comment]
I can confirm changing `(JarEntry. path)` to `(JarEntry. (str/replace path #”\\” “/“))` fixes the problem.

**Comment by tonsky** [comment]
Thanks! Want to provide a PR? Make sure to use java.io.File.separator in substitution instead of hard-coding `\`

**Comment by mmmdreg** [comment]
@tonsky can you please check the PR when you have a chance?
