### ISSUE TITLE
Merge META-INF/services/** on the fly

### ISSUE THREAD

**Issue by tonsky** [tonsky/uberdeps#2]

**Comment by pmonks** [comment]
The lack of this will cause major breakage when using certain Java libraries (e.g. [TrueVFS](http://truevfs.net/)).

**Comment by tonsky** [comment]
Yeah. Do you want to provide a PR?

**Comment by pmonks** [comment]
Not especially, but you may be able to adapt code from the [PR I submitted to leiningen back in the day](https://github.com/technomancy/leiningen/pull/1456), which [fixed this exact same issue there](https://github.com/technomancy/leiningen/issues/1455).
