### ISSUE TITLE
Uberjar returns null while executing .getResource on a resource directory but not on a resource file

### ISSUE THREAD

**Issue by manuviswam** [tonsky/uberdeps#20]
I have a project with the structure 
uberjardemo
     |
     ---- resources
     |              |
     |              ---- directory
     |                           |
     |                           ---- file.txt
     ----- src
     |          |
     |          ------ main
     |                         |
     |                         ----- uberjardemo
     |                                        |
     |                                        ----- demo.clj
     ---- deps.edn

I am trying to find the protocol of the directory under the resources folder (this should be "file" when running directly and "jar" when running from an uberjar)

The code for demo.clj is
```
(ns uberjardemo.demo)

(defn -main
  "The entry-point for our app"
  [& args]
  (prn "protocol of file" (.getProtocol (.getResource (ClassLoader/getSystemClassLoader) "directory/file.txt"))) ;Protocol of file "jar"
  (prn "protocol of directory" (.getProtocol (.getResource (ClassLoader/getSystemClassLoader) "directory/"))) ;NullPointerException
  )
```

And the content of deps.edn is
```
{:paths   ["src/main" "resources" ]
 :deps    {org.clojure/clojure            {:mvn/version "1.10.0"}}
 :aliases {:uberjar  {:extra-deps {uberdeps {:mvn/version "0.1.4"}}
                      :main-opts  ["-m" "uberdeps.uberjar --target target/demo.jar"]}}}
```

While I run this code directly from clojure, it works. But when I build the jar using the command `clojure -A:uberjar` and execute it using `java -cp target/demo.jar clojure.main -m uberjar.demo` only the second `prn` statement throws a `NullPointerException` since `(.getResource (ClassLoader/getSystemClassLoader) "directory/")` returns null.

**Comment by tonsky** [comment]
Can you check with 1.0.0? I was not putting directory entries into the jar, but starting from 1.0.0 I now do. Thanks!

**Comment by manuviswam** [comment]
Works with 1.0.0 Thank you.
