### ISSUE TITLE
Ability to enable Multi-Release flag in META-INF/MANIFEST.MF

### ISSUE THREAD

**Issue by gavinkflam** [tonsky/uberdeps#22]
## Feature

Introduce an option to enable the `Multi-Release: true` flag in META-INF/MANIFEST.MF.

https://openjdk.java.net/jeps/238

## Use cases

Some libraries (e.g. log4j2) provide multi-release JAR ("MRJAR").

We have to enable this flag in the generated uberjar in order to have those libraries working properly.

**Comment by tonsky** [comment]
That can make a great contribution. I have two questions:

- It the new option the only thing needed to actually have multi-release? I mean, if we add it, does it become useful?
- Can you change the option from `--multi-release (true|false)` to just `--multi-release`? I think that’s the convention for boolean keys in Bash

Thanks!

**Comment by gavinkflam** [comment]
## if we add it, does it become useful?

Yup. It enables MRJAR dependencies (e.g. log4j2) to work.

## change the option from --multi-release (true|false) to just --multi-release

That's reasonable. I guess I can leverage https://github.com/clojure/tools.cli for that.

**Comment by tonsky** [comment]
Please don’t add any dependencies. Let me merge your request and I’ll rewrite the option parsing code. I opened it now and realized it only supports key-value pairs

**Comment by tonsky** [comment]
Published https://clojars.org/uberdeps/versions/0.1.10. Thank you!
