### ISSUE TITLE
NoSuchMethodError when building executable

### ISSUE THREAD

**Issue by stopachka** [tonsky/uberdeps#26]
Hey team, am falling into a bit of a noob issue, and would love some help digging deeper if you can spare the time. 

I am trying to set up a jar, which i could deploy to something like google app engine. To do this, I am following the readme to set up an executable: https://github.com/tonsky/uberdeps#creating-an-executable-jar

Here's my code so far:
https://github.com/stopachka/clap/tree/uberdeps

When I run 

```
clj -e "(compile 'clap.core)"
clj -A:uberjar --main-class clap.core
java -jar target/clap.core
```

I get: 

```
Exception in thread "main" java.lang.NoSuchMethodError: 'java.lang.Object clojure.lang.Util.loadWithClass(java.lang.String, java.lang.Class)'
	at clap.core.<clinit>(Unknown Source)
```

If I try to run the classes directly: 

```
java -cp `clj -Spath` clap.core  
```

The server boots up, which makes me think things are okay at this stage. 

If I unzip the jar, I see something like this: 

![image](https://user-images.githubusercontent.com/984574/85355949-88343780-b4c2-11ea-96a5-35e59cb778ab.png)

which also seems fine. 

I _think_ the issue is happening at the uberjar stage, but am not sure how to dig deeper from the error message above. Any thoughts much appreciated

**Comment by tonsky** [comment]
Adding this

```
org.clojure/clojure {:mvn/version "1.10.0"}
```

to `:deps` fixes it. I’ll look further into why some default clojure version isn’t linked or if it should at all.

**Comment by stopachka** [comment]
Thanks Nikita!

**Comment by tonsky** [comment]
Added a note in the README 07722fc
