### ISSUE TITLE
*print-namespace-maps* binding problem in REPL

### ISSUE THREAD

**Issue by jdf-id-au** [tonsky/uberdeps#29]
I'm getting
`Exception in thread "main" Syntax error compiling at (`[uberdeps/api.clj:19:1](https://github.com/tonsky/uberdeps/blame/85df129dc044dcce3a9a09a7aa043fcaa001dce2/src/uberdeps/api.clj#L19)`)` caused by
`java.lang.IllegalStateException: Can't change/establish root binding of: *print-namespace-maps* with set` when trying to require uberdeps for use at the REPL within an established project (happens during REPL startup, and causes jvm to exit.). It doesn't happen when I require uberdeps for use at the REPL within a fresh, empty project.

I'm struggling to work out why this happens—do you have any suggestions?

**Comment by tonsky** [comment]
Oops, this was for dev time only. Pushed 1.0.1 with this removed. Sorry!

**Comment by jdf-id-au** [comment]
Your speed is blinding!
