### ISSUE TITLE
Use :replace-deps to simplify recommended project setup in the README

### ISSUE THREAD

**Issue by thenonameguy** [tonsky/uberdeps#32]
With clojure cli version: 1.10.1.727
I can add an alias in my project `deps.edn` like so:
```
:uberjar  {:replace-deps {uberdeps/uberdeps {:mvn/version "1.0.0"}}
           :main-opts    ["-m" "uberdeps.uberjar"]}
```
and invoke it with:
`clj -A:uberjar`
and the classpath will only contain the uberdeps dependency.

This makes project setup way less effort. Consider recommending this approach in the README.
For older clojure cli versions `clj -T:uberjar -M:uberjar` is an alternative.

**Comment by tonsky** [comment]
Nice! Thank you
