### ISSUE TITLE
Fix bash alias recommendation

### ISSUE THREAD

**Issue by imrekoszo** [tonsky/uberdeps#33]
Unfortunately, `clj -Sdeps '{:deps {uberdeps/uberdeps {:mvn/version "1.0.2"}}}' -m uberdeps.uberjar` does not

> replace whatever is in your deps.edn with uberdeps

This can be verified by running `clj -Sdeps '{:deps {uberdeps/uberdeps {:mvn/version "1.0.2"}}}' -Stree`.

I'd recommend updating that part of the readme to `clj -Sdeps '{:aliases {:uberjar {:replace-deps {uberdeps/uberdeps {:mvn/version "1.0.2"}}}}}' -M:uberjar -m uberdeps.uberjar`. (assuming clojure tools >= 1.9.0.326 for -M support and >= 1.10.1.672 for replace-deps support)

Like above, deps of this can be verified by running `clj -Sdeps '{:aliases {:uberjar {:replace-deps {uberdeps/uberdeps {:mvn/version "1.0.2"}}}}}' -A:uberjar -Stree`

**Comment by tonsky** [comment]
Fixed in #34

**Comment by imrekoszo** [comment]
Thank you!
