### ISSUE TITLE
Missing required argument for "-M ALIASES"

### ISSUE THREAD

**Issue by AntonOellerer** [tonsky/uberdeps#37]
Hey, 
First off, thank you very much for this useful project.
When testing it, I noticed that, when using the originally specified shell script to create an uberjar, I get the error notification `Missing required argument for "-M ALIASES"`.
The `clojure` manpages say the following for me:
```man
       -M:alias
              Concatenated main option aliases, ex: -M:test
```
When removing the `-M` flag from the script, everything runs as expected.
Do you know what my problem here might be?
Best regards
Anton Oellerer

**Comment by tonsky** [comment]
Hello Anton!

I am as confused about it as you are. From my understanding, bare `-M` is now mandatory for running main functions in `clj`, but it has not always been. They changed it at some point.

Can you try `brew upgrade clojure` and see if it works as specified in README?

**Comment by AntonOellerer** [comment]
Hey tonsky,
I am really sorry for posting this unfinished issue, typical monday...
The specifications of my machine:
- fedora 33, kernel 5.9
- clojure 1.10.1
- uberdeps 1.0.3
- openjdk 15.0.1

**Comment by AntonOellerer** [comment]
Is it possible you meant the `-m` flag?
The manpage says:
```
   main-opts
       -m, --main ns-name
              Call the -main function from namespace w/args
```

**Comment by tonsky** [comment]
The command-line `clj` script is a project with its own version. Unlike Clojure, it updates very often and breaks compatibility quite often too. This is what I have:

```
[~/ws/skija] clj -h
Version: 1.10.1.727
...
```

**Comment by AntonOellerer** [comment]
Hey,
I upgraded clj to `1.10.1.739` and now it works, sorry for the trouble!
