### ISSUE TITLE
Handle non-existing parent directory

### ISSUE THREAD

**Issue by jorinvo** [tonsky/uberdeps#4]
Hi, thanks for this simple tool!

When I first tried to run it I got an error:

```
[uberdeps] Packaging target/letsdo.events.jar...
Exception in thread "main" java.io.FileNotFoundException: target/myproject.jar (No such file or directory)
```

After creating the `target` directory manually, the error is resolved.

Could `uberdeps` create the parent directories automatically or show a useful error message to tell one that the problem is not that the `.jar` file does not exist, but that the directory does not exist? It would have saved me a few moments of wondering what's wrong :)

**Comment by tonsky** [comment]
Thanks! Fixed in 0.1.2
