### ISSUE TITLE
Not everything in `:paths` is making it into the jar

### ISSUE THREAD

**Issue by danielneal** [tonsky/uberdeps#43]
I'm building a project using the "Quick & Dirty" uberdeps setup. 
I have a few paths in addition to source in my `deps.edn`.

```clojure
{:paths ["src" "resources" "migrations" "java-classes" "classes"] ...}
```

When I run the uberdeps command, it looks like it's including those directories: 

```
$ clj -M:uberjar --main-class sqa.main --target target/sqa-app.jar
[uberdeps] Packaging target/sqa-app.jar...
+ classes/**
+ java-classes/**
+ migrations/**
+ resources/**
+ src/**
```

But in the jar itself, `migrations/**` and `resources/**` are absent. 

```
$ jar -tf sqa-app.jar | grep ^migrations 
<tumbleweed>
```

I think I'm most likely doing something wrong, or have misunderstood how uberjars work, but I'm not sure what. Any advice much appreciated!

**Comment by tonsky** [comment]
It includes everything under migrations, not the migrations folder itself. The :paths key/resource loading work the similar way
