### ISSUE TITLE
Using aliases with replace-deps and replace-paths doesn't seem to replace deps and paths

### ISSUE THREAD

**Issue by edahlseng** [tonsky/uberdeps#46]
Hi there! I'm having some trouble using aliases in a single `deps.edn` file (rather than a separate `deps.edn` file), but perhaps I'm misunderstanding how this should work. Here's what I'm trying to do:
* Default options in `deps.edn` file specify dependencies and paths as needed for the project
* AOT compile Clojure sources
* Bundle _only_ the classes from AOT compilation

My `deps.edn` file:
```edn
{:deps {org.clojure/clojure {:mvn/version "1.10.0"}
        ...}
 :paths ["sources"]
 :aliases {:aot-compile {:extra-paths ["classes"]}
           :package {:replace-deps {} :replace-paths ["classes"]}
           :packager {:replace-deps {uberdeps/uberdeps {:mvn/version "1.1.1"}}
                      :replace-paths []}}}
```

Steps that I'm running:
```shell
clojure -Aaot-compile --eval "(compile 'main.core)"
clojure -M:packager --main uberdeps.uberjar --aliases package --target output.jar --main-class main.core
```

At this point, I expect `output.jar` to include no Clojure sources, but instead it includes all of the Clojure sources for the project, as well as for the dependencies.

Instead, if I use a separate `package.deps.edn` file:
```edn
{:deps {}
 :paths ["classes"]}
```

And run the following steps:
```shell
clojure -Aaot-compile --eval "(compile 'main.core)"
clojure -M:packager --main uberdeps.uberjar --deps-file package.deps.edn --target output.jar --main-class main.core
```

It appears to work as I expect. Is there any way for me to get this behavior using a single `deps.edn` file?

**Comment by tonsky** [comment]
Just pushed 1.1.2, try with it, it should work now
