### ISSUE TITLE
Sorting the paths affects precedence of duplicate entries

### ISSUE THREAD

**Issue by jonathn** [tonsky/uberdeps#48]
The fact that the paths get sorted before being added to the jar (https://github.com/tonsky/uberdeps/blob/1.1.3/src/uberdeps/api.clj#L244) doesn't seem to match my expectation that directories added via `:extra-path` should come earlier on the classpath such that duplicate entries (like config files) can be overridden (and guarantee to be the one ending up in the jar), for example, by specifying an alias when creating the uberjar.

It seems to work the way I expect if `(sort ...)` is replaced by `(reverse ...)` -- so that extra-path entries come first.
Alternatively, the paths could be assembled in that order in the first place, matching what gets returned by `clj -Spath -A:myalias`.

**Comment by tonsky** [comment]
I guess we can try to replicate what tools.deps does, specifically

```clj
{:paths ["p3" "p1" "p2"]
 :aliases
 {:a {:paths         ["ap3" "ap1" "ap2"]
      :replace-paths ["ar3" "ar1" "ar2"]
      :extra-paths   ["ae3" "ae1" "ae2"]}
  :b {:paths         ["bp3" "bp1" "bp2"]
      :replace-paths ["br3" "br1" "br2"]
      :extra-paths   ["be3" "be1" "be2"]}
  :c {:extra-paths   ["ce3" "ce1" "ce2"]}
  :d {:extra-paths   ["de3" "de1" "de2"]}}}
```

will get you

```
clj -Spath -A:a:b        
ae3:ae1:ae2:be3:be1:be2:ap3:ap1:ap2:bp3:bp1:bp2:ar3:ar1:ar2:br3:br1:br2

clj -Spath -A:b:a
be3:be1:be2:ae3:ae1:ae2:bp3:bp1:bp2:ap3:ap1:ap2:br3:br1:br2:ar3:ar1:ar2

clj -Spath -A:c:d
ce3:ce1:ce2:de3:de1:de2:p3:p1:p2

clj -Spath -A:d:c
de3:de1:de2:ce3:ce1:ce2:p3:p1:p2
```

Looks like it’s something along the lines of

```
(concat
  (collect :extra-paths aliases)
  (or
    (concat
      (collect :paths aliases)
      (collect :replace-paths aliases))
    :paths))
```

Would that work for you?

**Comment by jonathn** [comment]
Sounds good

**Comment by tonsky** [comment]
Pushed 1.1.4
