### ISSUE TITLE
How to use generated jar file

### ISSUE THREAD

**Issue by jorinvo** [tonsky/uberdeps#5]
As someone not so familiar with Clojure and jars, it would be very helpful to have a little information on how to use the resulting jar.
What I tried is running a Clojure module inside the jar but that doesn't seem to be the way it works:

```
java -jar target/myproject.jar -m clojure.main
```

 I would really appreciate any hints here, thanks :)

**Comment by tonsky** [comment]
It’s 

java -cp target/myproject.jar clojure.main -m <your namespace with main>

Best,
Nikita

**Comment by jorinvo** [comment]
Awesome, thank you! This works perfectly. I mentioned it in the README. Discard it if you think it's not that useful to others. I don't mind :)
