### ISSUE TITLE
If data_readers cljc has reader conditionals: "No dispatch macro for ?"

### ISSUE THREAD

**Issue by CmdrDats** [tonsky/uberdeps#51]
In particular, when including `tick` (or really, transitively, `com.widdindustries/time-literals`), its data_readers.cljc trips things up: https://github.com/henryw374/time-literals/blob/master/src/data_readers.cljc

Getting:
```
Execution error at uberdeps.api/fn (api.clj:108).
No dispatch macro for: ?
```

It seems to be with the `edn/read-string`, since it doesn't handle the reader conditionals: https://github.com/tonsky/uberdeps/blob/master/src/uberdeps/api.clj#L108 

I tried to add the reader function to see if I can create a PR to fix it:

```clojure
(clojure.edn/read-string
  {:readers {'? (fn [b] b)}}
  "#?(:clj 1 :cljs 2)")
; Execution error at services.slack/eval35759 (REPL:188).
; No dispatch macro for: ?
```

but it seems lower level, since if I change to `#t`, for example, I get:

```clojure
(clojure.edn/read-string
  {:readers {'? (fn [b] b)}}
  "#t(:clj 1 :cljs 2)")
; Execution error at services.slack/eval35755 (REPL:182).
; No reader function for tag t
``` 

Not entirely sure what to suggest - I thought there was a way to say what environment we're reading in with edn/read-string, but I can't seem to find it.

**Comment by tonsky** [comment]
`#?` is reader conditional controlled by `:read-cond` option in `read`. I don’t think edn reader can read them at all. They are not part of EDN format.

Interestingly, `read` doesn’t save the day either: https://twitter.com/nikitonsky/status/1646193258681323521

So I falled back to naive string concatenation. I just pushed 1.3.0 with that change included. Let me know if that fixes the issue

**Comment by CmdrDats** [comment]
Wow, that was fast - amazing, thank you! Seems to work perfectly 🎉  

Weird that there's no native way of handling this in Clojure :'(

**Comment by tonsky** [comment]
Well, technically you’re supposed to just put multiple `data_readers.clj/c` into jar without merging (zip format allows to have multiple files with the same name, and Clojure expects there to be many), but unfortunately Java’s zip implementation checks and forbids that

**Comment by CmdrDats** [comment]
ugh.. incidental complexity and rabbit warrens... 🙈

**Comment by imrekoszo** [comment]
Looks like this change can create unreadable code when multiple data readers maps have the same key. In fact, the examples in the test appear to be unreadable (note the duplicate `common` keys):

```clojure
{project-a a
 common A
 project-b #?{:clj clj-b :cljs cljs-b}
 #?@{:clj [clj-only clj]}
 #?@{:cljs [cljs-only cljs]}
 common B}

{project-a a
 common A
 project-c c
 common C}
```

Stumbled upon this after bumping from 1.0.4 to 1.4.0:

```
clojure.lang.LispReader$ReaderException: java.lang.IllegalArgumentException: Duplicate key: time/period
 	at clojure.lang.LispReader.read(LispReader.java:316)
 	at clojure.lang.LispReader.read(LispReader.java:218)
 	at clojure.lang.LispReader.read(LispReader.java:207)
 	at clojure.core$read.invokeStatic(core.clj:3794)
 	at clojure.core$load_data_reader_file.invokeStatic(core.clj:8047)
...
```
