### ISSUE TITLE
Ability to select duplicated file to use

### ISSUE THREAD

**Issue by piranha** [tonsky/uberdeps#9]
I get message like that:
```
! Duplicate entry "logback.xml" from "src/**" already seen in "org.springframework.build/aws-maven 5.0.0.RELEASE"
```

and resulting uberjar contains wrong logback.xml :) I'm not sure what's the best way to proceed, maybe exclusions could (optionally?) match for project name.

**Comment by tonsky** [comment]
0.1.4 should do it
